image: node:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Iniciando o estágio de build"
    - cd somativa1devops
    - npm install
    - npm run build

test:
  stage: test
  script:
    - echo "Iniciando o estágio de testes"
    - cd somativa1devops
    - npm test

deploy:
  stage: deploy
  script:
    - echo "Iniciando o estágio de deploy"
    - cd somativa1devops